apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift --build=build-config --build-repo=https://github.com/poggdogg/prime-playground.git
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: dotnet-webapi
  name: dotnet-webapi
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: dotnet-webapi:latest
  postCommit: {}
  resources: 
    requests:
      cpu: "300m"
      memory: "512Mi"
    limits:
      cpu: "1" 
      memory: "1024Mi" 

  runPolicy: Serial
  source:
    contextDir: prime-dotnet-webapi/
    git:
      ref: develop
      uri: https://github.com/poggdogg/prime-playground.git
    type: Git
  strategy:
    dockerStrategy: 
      from:
        kind: "ImageStreamTag"
        name: "sdk:2.2"
      runtimeImage:
        kind: "ImageStreamTag"
        name: "aspnet:2.2"
      runtimeArtifacts: 
      - sourcePath: "."
        destinationDir: "/tmp"
    type: Dockerfile
    dockerfile: |-
      FROM sdk:2.2 AS build
      WORKDIR /tmp
      ENV WORKDIR /tmp
      ENV ASPNETCORE_ENVIRONMENT Development
      # Copy csproj and restore as distinct layers
      RUN mkdir -p $WORKDIR && \ 
          chown -R 1000:1000 $WORKDIR
      COPY *.csproj $WORKDIR
      RUN dotnet restore
      # Copy everything else and build
      COPY . $WORKDIR
      RUN dotnet publish -c Release -o out
      # Build runtime image
      FROM aspnet:2.2 AS runtime
      COPY --from=build $WORKDIR .
      EXPOSE 8080 5001
      ENV ASPNETCORE_ENVIRONMENT Development
      ENTRYPOINT ["/usr/bin/dotnet", "prime.dll"]

  triggers:
  - type: ConfigChange
status:
  lastVersion: 0
