apiVersion: v1
kind: BuildConfig
metadata:
  annotations:
    kompose.cmd: kompose convert --provider=openshift --build=build-config --build-repo=https://github.com/poggdogg/prime-playground.git
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: nginx-angular
  name: nginx-angular
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: nginx-angular:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: prime-angular-frontend/
    git:
      ref: develop
      uri: https://github.com/poggdogg/prime-playground.git
    type: Git
  strategy:
    dockerStrategy: {}
    type: Docker
  triggers:
  - type: ConfigChange
status:
  lastVersion: 0
